name: Build and push to ECR
on: { workflow_dispatch: {} }

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "954976321418"
  ECR_REPO_NAME: job-scraper
  IMAGE_TAG: v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure ECR repo exists
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" >/dev/null 2>&1 \
          || aws ecr create-repository --repository-name "$ECR_REPO_NAME"

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region "${AWS_REGION}" \
          | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # Build Playwright image for linux/amd64 (Fargate target) and push
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}
