# Toggle sources here. Add/change companies as needed.

linkedin_serpapi:
  enabled: false
  query: "Data Scientist"
  location: "Israel"

# LinkedIn via SearchApi.io Google Jobs (requires SEARCHAPI_API_KEY in .env)
searchapi_linkedin:
  enabled: false
  query: "Data Scientist"
  location: "Israel"

# LinkedIn direct automation using Playwright (requires credentials in .env)
linkedin_playwright:
  enabled: true
  query: "Data Scientist"
  location: "Israel"
  headless: true
  max_jobs: 25

# Greenhouse boards API, no API key needed
# Use the company board slug from https://boards.greenhouse.io/<slug>
# Examples below are known to be valid at time of writing.
greenhouse:
  enabled: false
  title_keywords: ["data scientist", "machine learning", "ml engineer"]
  companies:
    - lemonade
    - riskified
    - fiverr
    - appsflyer
    - similarweb

# Lever postings API, no API key needed
# Use company slug from https://jobs.lever.co/<slug>
lever:
  enabled: false
  title_keywords: ["data scientist", "machine learning", "ml engineer"]
  companies:
    - via
    - pagaya
    - vastdata 